### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by Error-404500** [A86K/Archlinux#1]
It will not work:
 
 ​`echo​ ​"​en_US.UTF-8 UTF-8​"​ ​>​ /etc/locale.gen 
 ​echo​ ​'​LANG="us_US.UTF-8"​'​ ​>​ /etc/locale.conf`
You need to use chroot and also remove one of the line. Because the first command rewrites the file and another also do the same thing

**Comment by A86K** [comment]
Changed!



Пн, 20 дек. 2021 г. в 14:24, Avengerist ***@***.***>:
